apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: abinash8/myrepo:lts
        ports:
        - containerPort: 8000
        
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec: 
  selector:
    app: app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer

